### ISSUE TITLE
Cursors not showing sometimes

### ISSUE THREAD

**Issue by TheHyperZtar** [catppuccin/cursors#53]
Hi, I've been using catppuccin's cursors and I've noticed that sometimes in apps like gparted, vscode, spotify, some file pickers, etc, the cursor disappears (more evident in gparted) and in others like rofi it appears somewhat cropped sometimes, I've been using them in nixos with hyprland and I've already tried several solutions but none of them worked, other cursors like Bibata's don't have this problem

**Comment by use-the-fork** [comment]
+1 here.

**Comment by arminius-smh** [comment]
:o https://github.com/hyprwm/Hyprland/issues/7335 might also not be related to this theme and is an upstream issue isntead? idk anymore

**Comment by sgoudham** [comment]
The hyprcursor implementation in this repository is not ideal, evident by the number of open issues. 

I don't use hyperland so it would require someone to look through the code and try to reimplement support for it in a way that addresses the concerns raised in #31

**Comment by arminius-smh** [comment]
Okay, I believe this issue here is related to the usage of pngs instead of svgs, I tried the hyprcursor theme with svgs and my cursor is now shown in xwayland apps

Not sure if the underlying issue has something to do with the pngs here or with Hyprland itself

Sadly I don't know how to fix the concerns in the linked issue/it's also a bit hard to go through and figure out what exactly has to be done to fix it entirely and use svgs again, but fixing that issue with svgs should resolve this one as well, I think

**Comment by sgoudham** [comment]
The cursors were based on SVGs before. As noted in that issue, @kerichdev found some other issues with it and changed it to PNGs. 

We should probably move back to SVGs given that the frequency of issues is now higher than it was before.
